 SELECT 
        A.TRANSACTION_DATE,
            TO_VARCHAR(ROUND(SUM(CASE
                WHEN B.CURRENCY_CODE <> 'EUR' THEN C.EXCHANGE_RATE_TO_EUR * A.AMOUNT 
                ELSE A.AMOUNT 
            END), 2)) AS SUM_AMOUNT_EUR
        FROM Payments A 
        INNER JOIN Currencies B ON A.CURRENCY = B.CURRENCY_ID
        LEFT JOIN Currency_Rates C ON B.CURRENCY_ID = C.CURRENCY_ID AND A.TRANSACTION_DATE = C.EXCHANGE_DATE
        LEFT JOIN Blacklist D ON A.USER_ID_SENDER = D.USER_ID AND D.BLACKLIST_END_DATE IS NULL 
        WHERE B.END_DATE IS NULL AND D.USER_ID IS NULL 
        GROUP BY A.TRANSACTION_DATE 
